#ifndef FAULT_CODES_H
#define FAULT_CODES_H

#define FAULT_NEGATIVE_RELEASE            1
#define FAULT_INVALID_COST_EXPONENTS      2
#define FAULT_INCONSISTENT_OBJVALS        3
#define FAULT_START_BEFORE_RELEASE        4
#define FAULT_END_AFTER_DEADLINE          5
#define FAULT_START_BEFORE_LAG            6
#define FAULT_NO_TRANSFORMATION           7
#define FAULT_CRITICAL_PATH_INFEASIBLE    8
#define FAULT_NEGATIVE_TIME_INTERVAL      9
#define FAULT_WINDOW_EXTENSION_SUM        10
#define FAULT_WINDOW_EXTENSION_JOB_SUM    11
#define FAULT_TIME_LIMIT_NEEDED						12
#define FAULT_DATABASE_FAILED							13
#define FAULT_OUT_OF_MEMORY               14
#endif
