// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef DB_OBJECTS_ODB_HXX
#define DB_OBJECTS_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "db_objects.hpp"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // DBConfigKV
  //
  template <>
  struct class_traits< ::DBConfigKV >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBConfigKV >
  {
    public:
    typedef ::DBConfigKV object_type;
    typedef ::DBConfigKV* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DBConfig
  //
  template <>
  struct class_traits< ::DBConfig >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBConfig >
  {
    public:
    typedef ::DBConfig object_type;
    typedef ::DBConfig* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DBResult
  //
  template <>
  struct class_traits< ::DBResult >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBResult >
  {
    public:
    typedef ::DBResult object_type;
    typedef ::DBResult* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DBSolution
  //
  template <>
  struct class_traits< ::DBSolution >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBSolution >
  {
    public:
    typedef ::DBSolution object_type;
    typedef ::DBSolution* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DBSolutionJob
  //
  template <>
  struct class_traits< ::DBSolutionJob >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBSolutionJob >
  {
    public:
    typedef ::DBSolutionJob object_type;
    typedef ::DBSolutionJob* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DBIntermediate
  //
  template <>
  struct class_traits< ::DBIntermediate >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBIntermediate >
  {
    public:
    typedef ::DBIntermediate object_type;
    typedef ::DBIntermediate* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DBError
  //
  template <>
  struct class_traits< ::DBError >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBError >
  {
    public:
    typedef ::DBError object_type;
    typedef ::DBError* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DBExtendedMeasure
  //
  template <>
  struct class_traits< ::DBExtendedMeasure >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DBExtendedMeasure >
  {
    public:
    typedef ::DBExtendedMeasure object_type;
    typedef ::DBExtendedMeasure* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // DBConfigKV
  //
  template <typename A>
  struct pointer_query_columns< ::DBConfigKV, id_sqlite, A >
  {
    // cfg
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    cfg_type_;

    static const cfg_type_ cfg;

    // key
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    key_type_;

    static const key_type_ key;

    // value
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    value_type_;

    static const value_type_ value;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename pointer_query_columns< ::DBConfigKV, id_sqlite, A >::cfg_type_
  pointer_query_columns< ::DBConfigKV, id_sqlite, A >::
  cfg (A::table_name, "\"cfg\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBConfigKV, id_sqlite, A >::key_type_
  pointer_query_columns< ::DBConfigKV, id_sqlite, A >::
  key (A::table_name, "\"key\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBConfigKV, id_sqlite, A >::value_type_
  pointer_query_columns< ::DBConfigKV, id_sqlite, A >::
  value (A::table_name, "\"value\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBConfigKV, id_sqlite, A >::id_type_
  pointer_query_columns< ::DBConfigKV, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <>
  class access::object_traits_impl< ::DBConfigKV, id_sqlite >:
    public access::object_traits< ::DBConfigKV >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // cfg
      //
      long long cfg_value;
      bool cfg_null;

      // key
      //
      details::buffer key_value;
      std::size_t key_size;
      bool key_null;

      // value
      //
      details::buffer value_value;
      std::size_t value_size;
      bool value_null;

      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct cfg_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBConfigKV, id_common >:
    public access::object_traits_impl< ::DBConfigKV, id_sqlite >
  {
  };

  // DBConfig
  //
  template <typename A>
  struct query_columns< ::DBConfig, id_sqlite, A >
  {
    // name
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    name_type_;

    static const name_type_ name;

    // time_limit
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    time_limit_type_;

    static const time_limit_type_ time_limit;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::DBConfig, id_sqlite, A >::name_type_
  query_columns< ::DBConfig, id_sqlite, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename query_columns< ::DBConfig, id_sqlite, A >::time_limit_type_
  query_columns< ::DBConfig, id_sqlite, A >::
  time_limit (A::table_name, "\"time_limit\"", 0);

  template <typename A>
  const typename query_columns< ::DBConfig, id_sqlite, A >::id_type_
  query_columns< ::DBConfig, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  struct pointer_query_columns< ::DBConfig, id_sqlite, A >:
    query_columns< ::DBConfig, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::DBConfig, id_sqlite >:
    public access::object_traits< ::DBConfig >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // name
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // time_limit
      //
      long long time_limit_value;
      bool time_limit_null;

      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // entries
    //
    struct entries_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 2UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::odb::lazy_weak_ptr< ::DBConfigKV > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef sqlite::container_statements< entries_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        long long value_value;
        bool value_null;

        std::size_t version;
      };

      static void
      bind (sqlite::bind*,
            const sqlite::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      load (container_type&,
            statements_type&);
    };

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBConfig, id_common >:
    public access::object_traits_impl< ::DBConfig, id_sqlite >
  {
  };

  // DBResult
  //
  template <typename A>
  struct pointer_query_columns< ::DBResult, id_sqlite, A >
  {
    // run
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    run_type_;

    static const run_type_ run;

    // instance
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    instance_type_;

    static const instance_type_ instance;

    // score
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    score_type_;

    static const score_type_ score;

    // algorithm
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    algorithm_type_;

    static const algorithm_type_ algorithm;

    // config
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    config_type_;

    static const config_type_ config;

    // seed
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    seed_type_;

    static const seed_type_ seed;

    // optimal
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        bool,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    optimal_type_;

    static const optimal_type_ optimal;

    // feasible
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        bool,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    feasible_type_;

    static const feasible_type_ feasible;

    // lower_bound
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    lower_bound_type_;

    static const lower_bound_type_ lower_bound;

    // elapsed
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    elapsed_type_;

    static const elapsed_type_ elapsed;

    // cfg
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    cfg_type_;

    static const cfg_type_ cfg;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::run_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  run (A::table_name, "\"run\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::instance_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  instance (A::table_name, "\"instance\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::score_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  score (A::table_name, "\"score\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::algorithm_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  algorithm (A::table_name, "\"algorithm\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::config_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  config (A::table_name, "\"config\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::seed_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  seed (A::table_name, "\"seed\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::optimal_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  optimal (A::table_name, "\"optimal\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::feasible_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  feasible (A::table_name, "\"feasible\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::lower_bound_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  lower_bound (A::table_name, "\"lower_bound\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::elapsed_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  elapsed (A::table_name, "\"elapsed\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::cfg_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  cfg (A::table_name, "\"cfg\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBResult, id_sqlite, A >::id_type_
  pointer_query_columns< ::DBResult, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <>
  class access::object_traits_impl< ::DBResult, id_sqlite >:
    public access::object_traits< ::DBResult >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // run
      //
      details::buffer run_value;
      std::size_t run_size;
      bool run_null;

      // instance
      //
      details::buffer instance_value;
      std::size_t instance_size;
      bool instance_null;

      // score
      //
      double score_value;
      bool score_null;

      // algorithm
      //
      details::buffer algorithm_value;
      std::size_t algorithm_size;
      bool algorithm_null;

      // config
      //
      details::buffer config_value;
      std::size_t config_size;
      bool config_null;

      // seed
      //
      long long seed_value;
      bool seed_null;

      // optimal
      //
      long long optimal_value;
      bool optimal_null;

      // feasible
      //
      long long feasible_value;
      bool feasible_null;

      // lower_bound
      //
      double lower_bound_value;
      bool lower_bound_null;

      // elapsed
      //
      double elapsed_value;
      bool elapsed_null;

      // cfg
      //
      long long cfg_value;
      bool cfg_null;

      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct cfg_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 12UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBResult, id_common >:
    public access::object_traits_impl< ::DBResult, id_sqlite >
  {
  };

  // DBSolution
  //
  template <typename A>
  struct pointer_query_columns< ::DBSolution, id_sqlite, A >
  {
    // res
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    res_type_;

    static const res_type_ res;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename pointer_query_columns< ::DBSolution, id_sqlite, A >::res_type_
  pointer_query_columns< ::DBSolution, id_sqlite, A >::
  res (A::table_name, "\"res\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBSolution, id_sqlite, A >::id_type_
  pointer_query_columns< ::DBSolution, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <>
  class access::object_traits_impl< ::DBSolution, id_sqlite >:
    public access::object_traits< ::DBSolution >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // res
      //
      long long res_value;
      bool res_null;

      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // jobs
    //
    struct jobs_traits
    {
      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 2UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::std::shared_ptr< ::DBSolutionJob > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef sqlite::container_statements< jobs_traits > statements_type;

      struct data_image_type
      {
        // value
        //
        long long value_value;
        bool value_null;

        std::size_t version;
      };

      static void
      bind (sqlite::bind*,
            const sqlite::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      load (container_type&,
            statements_type&);
    };

    struct res_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBSolution, id_common >:
    public access::object_traits_impl< ::DBSolution, id_sqlite >
  {
  };

  // DBSolutionJob
  //
  template <typename A>
  struct pointer_query_columns< ::DBSolutionJob, id_sqlite, A >
  {
    // sol
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    sol_type_;

    static const sol_type_ sol;

    // job_id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    job_id_type_;

    static const job_id_type_ job_id;

    // start_time
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    start_time_type_;

    static const start_time_type_ start_time;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename pointer_query_columns< ::DBSolutionJob, id_sqlite, A >::sol_type_
  pointer_query_columns< ::DBSolutionJob, id_sqlite, A >::
  sol (A::table_name, "\"sol\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBSolutionJob, id_sqlite, A >::job_id_type_
  pointer_query_columns< ::DBSolutionJob, id_sqlite, A >::
  job_id (A::table_name, "\"job_id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBSolutionJob, id_sqlite, A >::start_time_type_
  pointer_query_columns< ::DBSolutionJob, id_sqlite, A >::
  start_time (A::table_name, "\"start_time\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBSolutionJob, id_sqlite, A >::id_type_
  pointer_query_columns< ::DBSolutionJob, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <>
  class access::object_traits_impl< ::DBSolutionJob, id_sqlite >:
    public access::object_traits< ::DBSolutionJob >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // sol
      //
      long long sol_value;
      bool sol_null;

      // job_id
      //
      long long job_id_value;
      bool job_id_null;

      // start_time
      //
      long long start_time_value;
      bool start_time_null;

      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct sol_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBSolutionJob, id_common >:
    public access::object_traits_impl< ::DBSolutionJob, id_sqlite >
  {
  };

  // DBIntermediate
  //
  template <typename A>
  struct pointer_query_columns< ::DBIntermediate, id_sqlite, A >
  {
    // res
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    res_type_;

    static const res_type_ res;

    // time
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    time_type_;

    static const time_type_ time;

    // iteration
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    iteration_type_;

    static const iteration_type_ iteration;

    // costs
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    costs_type_;

    static const costs_type_ costs;

    // bound
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    bound_type_;

    static const bound_type_ bound;

    // solution
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    solution_type_;

    static const solution_type_ solution;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename pointer_query_columns< ::DBIntermediate, id_sqlite, A >::res_type_
  pointer_query_columns< ::DBIntermediate, id_sqlite, A >::
  res (A::table_name, "\"res\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBIntermediate, id_sqlite, A >::time_type_
  pointer_query_columns< ::DBIntermediate, id_sqlite, A >::
  time (A::table_name, "\"time\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBIntermediate, id_sqlite, A >::iteration_type_
  pointer_query_columns< ::DBIntermediate, id_sqlite, A >::
  iteration (A::table_name, "\"iteration\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBIntermediate, id_sqlite, A >::costs_type_
  pointer_query_columns< ::DBIntermediate, id_sqlite, A >::
  costs (A::table_name, "\"costs\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBIntermediate, id_sqlite, A >::bound_type_
  pointer_query_columns< ::DBIntermediate, id_sqlite, A >::
  bound (A::table_name, "\"bound\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBIntermediate, id_sqlite, A >::solution_type_
  pointer_query_columns< ::DBIntermediate, id_sqlite, A >::
  solution (A::table_name, "\"solution\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBIntermediate, id_sqlite, A >::id_type_
  pointer_query_columns< ::DBIntermediate, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <>
  class access::object_traits_impl< ::DBIntermediate, id_sqlite >:
    public access::object_traits< ::DBIntermediate >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // res
      //
      long long res_value;
      bool res_null;

      // time
      //
      double time_value;
      bool time_null;

      // iteration
      //
      long long iteration_value;
      bool iteration_null;

      // costs
      //
      double costs_value;
      bool costs_null;

      // bound
      //
      double bound_value;
      bool bound_null;

      // solution
      //
      long long solution_value;
      bool solution_null;

      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct res_tag;
    struct solution_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBIntermediate, id_common >:
    public access::object_traits_impl< ::DBIntermediate, id_sqlite >
  {
  };

  // DBError
  //
  template <typename A>
  struct query_columns< ::DBError, id_sqlite, A >
  {
    // timestamp
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    timestamp_type_;

    static const timestamp_type_ timestamp;

    // run
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    run_type_;

    static const run_type_ run;

    // instance
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    instance_type_;

    static const instance_type_ instance;

    // algorithm
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    algorithm_type_;

    static const algorithm_type_ algorithm;

    // config
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    config_type_;

    static const config_type_ config;

    // seed
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    seed_type_;

    static const seed_type_ seed;

    // fault_code
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    fault_code_type_;

    static const fault_code_type_ fault_code;

    // error_id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    error_id_type_;

    static const error_id_type_ error_id;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::timestamp_type_
  query_columns< ::DBError, id_sqlite, A >::
  timestamp (A::table_name, "\"timestamp\"", 0);

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::run_type_
  query_columns< ::DBError, id_sqlite, A >::
  run (A::table_name, "\"run\"", 0);

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::instance_type_
  query_columns< ::DBError, id_sqlite, A >::
  instance (A::table_name, "\"instance\"", 0);

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::algorithm_type_
  query_columns< ::DBError, id_sqlite, A >::
  algorithm (A::table_name, "\"algorithm\"", 0);

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::config_type_
  query_columns< ::DBError, id_sqlite, A >::
  config (A::table_name, "\"config\"", 0);

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::seed_type_
  query_columns< ::DBError, id_sqlite, A >::
  seed (A::table_name, "\"seed\"", 0);

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::fault_code_type_
  query_columns< ::DBError, id_sqlite, A >::
  fault_code (A::table_name, "\"fault_code\"", 0);

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::error_id_type_
  query_columns< ::DBError, id_sqlite, A >::
  error_id (A::table_name, "\"error_id\"", 0);

  template <typename A>
  const typename query_columns< ::DBError, id_sqlite, A >::id_type_
  query_columns< ::DBError, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  struct pointer_query_columns< ::DBError, id_sqlite, A >:
    query_columns< ::DBError, id_sqlite, A >
  {
  };

  template <>
  class access::object_traits_impl< ::DBError, id_sqlite >:
    public access::object_traits< ::DBError >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // timestamp
      //
      long long timestamp_value;
      bool timestamp_null;

      // run
      //
      details::buffer run_value;
      std::size_t run_size;
      bool run_null;

      // instance
      //
      details::buffer instance_value;
      std::size_t instance_size;
      bool instance_null;

      // algorithm
      //
      details::buffer algorithm_value;
      std::size_t algorithm_size;
      bool algorithm_null;

      // config
      //
      details::buffer config_value;
      std::size_t config_size;
      bool config_null;

      // seed
      //
      long long seed_value;
      bool seed_null;

      // fault_code
      //
      long long fault_code_value;
      bool fault_code_null;

      // error_id
      //
      long long error_id_value;
      bool error_id_null;

      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBError, id_common >:
    public access::object_traits_impl< ::DBError, id_sqlite >
  {
  };

  // DBExtendedMeasure
  //
  template <typename A>
  struct pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >
  {
    // res
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    res_type_;

    static const res_type_ res;

    // key
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    key_type_;

    static const key_type_ key;

    // iteration
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    iteration_type_;

    static const iteration_type_ iteration;

    // time
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    time_type_;

    static const time_type_ time;

    // v_int
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    v_int_type_;

    static const v_int_type_ v_int;

    // v_double
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    v_double_type_;

    static const v_double_type_ v_double;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::res_type_
  pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  res (A::table_name, "\"res\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::key_type_
  pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  key (A::table_name, "\"key\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::iteration_type_
  pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  iteration (A::table_name, "\"iteration\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::time_type_
  pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  time (A::table_name, "\"time\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::v_int_type_
  pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  v_int (A::table_name, "\"v_int\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::v_double_type_
  pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  v_double (A::table_name, "\"v_double\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::id_type_
  pointer_query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <>
  class access::object_traits_impl< ::DBExtendedMeasure, id_sqlite >:
    public access::object_traits< ::DBExtendedMeasure >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // res
      //
      long long res_value;
      bool res_null;

      // key
      //
      details::buffer key_value;
      std::size_t key_size;
      bool key_null;

      // iteration
      //
      long long iteration_value;
      bool iteration_null;

      // time
      //
      double time_value;
      bool time_null;

      // v_int
      //
      long long v_int_value;
      bool v_int_null;

      // v_double
      //
      double v_double_value;
      bool v_double_null;

      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct res_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DBExtendedMeasure, id_common >:
    public access::object_traits_impl< ::DBExtendedMeasure, id_sqlite >
  {
  };

  // DBConfigKV
  //
  template <>
  struct alias_traits<
    ::DBConfig,
    id_sqlite,
    access::object_traits_impl< ::DBConfigKV, id_sqlite >::cfg_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::DBConfigKV, id_sqlite >
  {
    // cfg
    //
    typedef
    odb::alias_traits<
      ::DBConfig,
      id_sqlite,
      access::object_traits_impl< ::DBConfigKV, id_sqlite >::cfg_tag>
    cfg_alias_;
  };

  template <typename A>
  struct query_columns< ::DBConfigKV, id_sqlite, A >:
    query_columns_base< ::DBConfigKV, id_sqlite >
  {
    // cfg
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    cfg_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::DBConfig,
        id_sqlite,
        cfg_alias_ > >
    cfg_pointer_type_;

    struct cfg_type_: cfg_pointer_type_, cfg_column_type_
    {
      cfg_type_ (const char* t, const char* c, const char* conv)
        : cfg_column_type_ (t, c, conv)
      {
      }
    };

    static const cfg_type_ cfg;

    // key
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    key_type_;

    static const key_type_ key;

    // value
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    value_type_;

    static const value_type_ value;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::DBConfigKV, id_sqlite, A >::cfg_type_
  query_columns< ::DBConfigKV, id_sqlite, A >::
  cfg (A::table_name, "\"cfg\"", 0);

  template <typename A>
  const typename query_columns< ::DBConfigKV, id_sqlite, A >::key_type_
  query_columns< ::DBConfigKV, id_sqlite, A >::
  key (A::table_name, "\"key\"", 0);

  template <typename A>
  const typename query_columns< ::DBConfigKV, id_sqlite, A >::value_type_
  query_columns< ::DBConfigKV, id_sqlite, A >::
  value (A::table_name, "\"value\"", 0);

  template <typename A>
  const typename query_columns< ::DBConfigKV, id_sqlite, A >::id_type_
  query_columns< ::DBConfigKV, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  // DBConfig
  //
  // DBResult
  //
  template <>
  struct alias_traits<
    ::DBConfig,
    id_sqlite,
    access::object_traits_impl< ::DBResult, id_sqlite >::cfg_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::DBResult, id_sqlite >
  {
    // cfg
    //
    typedef
    odb::alias_traits<
      ::DBConfig,
      id_sqlite,
      access::object_traits_impl< ::DBResult, id_sqlite >::cfg_tag>
    cfg_alias_;
  };

  template <typename A>
  struct query_columns< ::DBResult, id_sqlite, A >:
    query_columns_base< ::DBResult, id_sqlite >
  {
    // run
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    run_type_;

    static const run_type_ run;

    // instance
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    instance_type_;

    static const instance_type_ instance;

    // score
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    score_type_;

    static const score_type_ score;

    // algorithm
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    algorithm_type_;

    static const algorithm_type_ algorithm;

    // config
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    config_type_;

    static const config_type_ config;

    // seed
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    seed_type_;

    static const seed_type_ seed;

    // optimal
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        bool,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    optimal_type_;

    static const optimal_type_ optimal;

    // feasible
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        bool,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    feasible_type_;

    static const feasible_type_ feasible;

    // lower_bound
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    lower_bound_type_;

    static const lower_bound_type_ lower_bound;

    // elapsed
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    elapsed_type_;

    static const elapsed_type_ elapsed;

    // cfg
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    cfg_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::DBConfig,
        id_sqlite,
        cfg_alias_ > >
    cfg_pointer_type_;

    struct cfg_type_: cfg_pointer_type_, cfg_column_type_
    {
      cfg_type_ (const char* t, const char* c, const char* conv)
        : cfg_column_type_ (t, c, conv)
      {
      }
    };

    static const cfg_type_ cfg;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::run_type_
  query_columns< ::DBResult, id_sqlite, A >::
  run (A::table_name, "\"run\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::instance_type_
  query_columns< ::DBResult, id_sqlite, A >::
  instance (A::table_name, "\"instance\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::score_type_
  query_columns< ::DBResult, id_sqlite, A >::
  score (A::table_name, "\"score\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::algorithm_type_
  query_columns< ::DBResult, id_sqlite, A >::
  algorithm (A::table_name, "\"algorithm\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::config_type_
  query_columns< ::DBResult, id_sqlite, A >::
  config (A::table_name, "\"config\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::seed_type_
  query_columns< ::DBResult, id_sqlite, A >::
  seed (A::table_name, "\"seed\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::optimal_type_
  query_columns< ::DBResult, id_sqlite, A >::
  optimal (A::table_name, "\"optimal\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::feasible_type_
  query_columns< ::DBResult, id_sqlite, A >::
  feasible (A::table_name, "\"feasible\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::lower_bound_type_
  query_columns< ::DBResult, id_sqlite, A >::
  lower_bound (A::table_name, "\"lower_bound\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::elapsed_type_
  query_columns< ::DBResult, id_sqlite, A >::
  elapsed (A::table_name, "\"elapsed\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::cfg_type_
  query_columns< ::DBResult, id_sqlite, A >::
  cfg (A::table_name, "\"cfg\"", 0);

  template <typename A>
  const typename query_columns< ::DBResult, id_sqlite, A >::id_type_
  query_columns< ::DBResult, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  // DBSolution
  //
  template <>
  struct alias_traits<
    ::DBResult,
    id_sqlite,
    access::object_traits_impl< ::DBSolution, id_sqlite >::res_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::DBSolution, id_sqlite >
  {
    // res
    //
    typedef
    odb::alias_traits<
      ::DBResult,
      id_sqlite,
      access::object_traits_impl< ::DBSolution, id_sqlite >::res_tag>
    res_alias_;
  };

  template <typename A>
  struct query_columns< ::DBSolution, id_sqlite, A >:
    query_columns_base< ::DBSolution, id_sqlite >
  {
    // res
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    res_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::DBResult,
        id_sqlite,
        res_alias_ > >
    res_pointer_type_;

    struct res_type_: res_pointer_type_, res_column_type_
    {
      res_type_ (const char* t, const char* c, const char* conv)
        : res_column_type_ (t, c, conv)
      {
      }
    };

    static const res_type_ res;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::DBSolution, id_sqlite, A >::res_type_
  query_columns< ::DBSolution, id_sqlite, A >::
  res (A::table_name, "\"res\"", 0);

  template <typename A>
  const typename query_columns< ::DBSolution, id_sqlite, A >::id_type_
  query_columns< ::DBSolution, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  // DBSolutionJob
  //
  template <>
  struct alias_traits<
    ::DBSolution,
    id_sqlite,
    access::object_traits_impl< ::DBSolutionJob, id_sqlite >::sol_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::DBSolutionJob, id_sqlite >
  {
    // sol
    //
    typedef
    odb::alias_traits<
      ::DBSolution,
      id_sqlite,
      access::object_traits_impl< ::DBSolutionJob, id_sqlite >::sol_tag>
    sol_alias_;
  };

  template <typename A>
  struct query_columns< ::DBSolutionJob, id_sqlite, A >:
    query_columns_base< ::DBSolutionJob, id_sqlite >
  {
    // sol
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    sol_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::DBSolution,
        id_sqlite,
        sol_alias_ > >
    sol_pointer_type_;

    struct sol_type_: sol_pointer_type_, sol_column_type_
    {
      sol_type_ (const char* t, const char* c, const char* conv)
        : sol_column_type_ (t, c, conv)
      {
      }
    };

    static const sol_type_ sol;

    // job_id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    job_id_type_;

    static const job_id_type_ job_id;

    // start_time
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    start_time_type_;

    static const start_time_type_ start_time;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::DBSolutionJob, id_sqlite, A >::sol_type_
  query_columns< ::DBSolutionJob, id_sqlite, A >::
  sol (A::table_name, "\"sol\"", 0);

  template <typename A>
  const typename query_columns< ::DBSolutionJob, id_sqlite, A >::job_id_type_
  query_columns< ::DBSolutionJob, id_sqlite, A >::
  job_id (A::table_name, "\"job_id\"", 0);

  template <typename A>
  const typename query_columns< ::DBSolutionJob, id_sqlite, A >::start_time_type_
  query_columns< ::DBSolutionJob, id_sqlite, A >::
  start_time (A::table_name, "\"start_time\"", 0);

  template <typename A>
  const typename query_columns< ::DBSolutionJob, id_sqlite, A >::id_type_
  query_columns< ::DBSolutionJob, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  // DBIntermediate
  //
  template <>
  struct alias_traits<
    ::DBResult,
    id_sqlite,
    access::object_traits_impl< ::DBIntermediate, id_sqlite >::res_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::DBSolution,
    id_sqlite,
    access::object_traits_impl< ::DBIntermediate, id_sqlite >::solution_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::DBIntermediate, id_sqlite >
  {
    // res
    //
    typedef
    odb::alias_traits<
      ::DBResult,
      id_sqlite,
      access::object_traits_impl< ::DBIntermediate, id_sqlite >::res_tag>
    res_alias_;

    // solution
    //
    typedef
    odb::alias_traits<
      ::DBSolution,
      id_sqlite,
      access::object_traits_impl< ::DBIntermediate, id_sqlite >::solution_tag>
    solution_alias_;
  };

  template <typename A>
  struct query_columns< ::DBIntermediate, id_sqlite, A >:
    query_columns_base< ::DBIntermediate, id_sqlite >
  {
    // res
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    res_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::DBResult,
        id_sqlite,
        res_alias_ > >
    res_pointer_type_;

    struct res_type_: res_pointer_type_, res_column_type_
    {
      res_type_ (const char* t, const char* c, const char* conv)
        : res_column_type_ (t, c, conv)
      {
      }
    };

    static const res_type_ res;

    // time
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    time_type_;

    static const time_type_ time;

    // iteration
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    iteration_type_;

    static const iteration_type_ iteration;

    // costs
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    costs_type_;

    static const costs_type_ costs;

    // bound
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    bound_type_;

    static const bound_type_ bound;

    // solution
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    solution_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::DBSolution,
        id_sqlite,
        solution_alias_ > >
    solution_pointer_type_;

    struct solution_type_: solution_pointer_type_, solution_column_type_
    {
      solution_type_ (const char* t, const char* c, const char* conv)
        : solution_column_type_ (t, c, conv)
      {
      }
    };

    static const solution_type_ solution;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::DBIntermediate, id_sqlite, A >::res_type_
  query_columns< ::DBIntermediate, id_sqlite, A >::
  res (A::table_name, "\"res\"", 0);

  template <typename A>
  const typename query_columns< ::DBIntermediate, id_sqlite, A >::time_type_
  query_columns< ::DBIntermediate, id_sqlite, A >::
  time (A::table_name, "\"time\"", 0);

  template <typename A>
  const typename query_columns< ::DBIntermediate, id_sqlite, A >::iteration_type_
  query_columns< ::DBIntermediate, id_sqlite, A >::
  iteration (A::table_name, "\"iteration\"", 0);

  template <typename A>
  const typename query_columns< ::DBIntermediate, id_sqlite, A >::costs_type_
  query_columns< ::DBIntermediate, id_sqlite, A >::
  costs (A::table_name, "\"costs\"", 0);

  template <typename A>
  const typename query_columns< ::DBIntermediate, id_sqlite, A >::bound_type_
  query_columns< ::DBIntermediate, id_sqlite, A >::
  bound (A::table_name, "\"bound\"", 0);

  template <typename A>
  const typename query_columns< ::DBIntermediate, id_sqlite, A >::solution_type_
  query_columns< ::DBIntermediate, id_sqlite, A >::
  solution (A::table_name, "\"solution\"", 0);

  template <typename A>
  const typename query_columns< ::DBIntermediate, id_sqlite, A >::id_type_
  query_columns< ::DBIntermediate, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  // DBError
  //
  // DBExtendedMeasure
  //
  template <>
  struct alias_traits<
    ::DBResult,
    id_sqlite,
    access::object_traits_impl< ::DBExtendedMeasure, id_sqlite >::res_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::DBExtendedMeasure, id_sqlite >
  {
    // res
    //
    typedef
    odb::alias_traits<
      ::DBResult,
      id_sqlite,
      access::object_traits_impl< ::DBExtendedMeasure, id_sqlite >::res_tag>
    res_alias_;
  };

  template <typename A>
  struct query_columns< ::DBExtendedMeasure, id_sqlite, A >:
    query_columns_base< ::DBExtendedMeasure, id_sqlite >
  {
    // res
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    res_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::DBResult,
        id_sqlite,
        res_alias_ > >
    res_pointer_type_;

    struct res_type_: res_pointer_type_, res_column_type_
    {
      res_type_ (const char* t, const char* c, const char* conv)
        : res_column_type_ (t, c, conv)
      {
      }
    };

    static const res_type_ res;

    // key
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    key_type_;

    static const key_type_ key;

    // iteration
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    iteration_type_;

    static const iteration_type_ iteration;

    // time
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    time_type_;

    static const time_type_ time;

    // v_int
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    v_int_type_;

    static const v_int_type_ v_int;

    // v_double
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    v_double_type_;

    static const v_double_type_ v_double;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::DBExtendedMeasure, id_sqlite, A >::res_type_
  query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  res (A::table_name, "\"res\"", 0);

  template <typename A>
  const typename query_columns< ::DBExtendedMeasure, id_sqlite, A >::key_type_
  query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  key (A::table_name, "\"key\"", 0);

  template <typename A>
  const typename query_columns< ::DBExtendedMeasure, id_sqlite, A >::iteration_type_
  query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  iteration (A::table_name, "\"iteration\"", 0);

  template <typename A>
  const typename query_columns< ::DBExtendedMeasure, id_sqlite, A >::time_type_
  query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  time (A::table_name, "\"time\"", 0);

  template <typename A>
  const typename query_columns< ::DBExtendedMeasure, id_sqlite, A >::v_int_type_
  query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  v_int (A::table_name, "\"v_int\"", 0);

  template <typename A>
  const typename query_columns< ::DBExtendedMeasure, id_sqlite, A >::v_double_type_
  query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  v_double (A::table_name, "\"v_double\"", 0);

  template <typename A>
  const typename query_columns< ::DBExtendedMeasure, id_sqlite, A >::id_type_
  query_columns< ::DBExtendedMeasure, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);
}

#include "db_objects-odb.ixx"

#include <odb/post.hxx>

#endif // DB_OBJECTS_ODB_HXX
